version: '2'

# -----------------------------------
# ENVIRONMENT VARIABLES
# -----------------------------------
# Required properties:
# Please create .env file (in this directory) and set the following values:
#
# CONFIG_SERVER_CONFIG_DIR=/your/config/folder/location
# -----------------------------------

services:

# -----------------------------------
# CONFIG SERVER [localhost:8070]
# -----------------------------------
  config:
    image: imamchishty/config-server
    ports:
      - "8070:8070"
    environment:
      CONFIG_DIR: ${CONFIG_SERVER_CONFIG_DIR}
    volumes:
      - ${CONFIG_SERVER_CONFIG_DIR}:${CONFIG_SERVER_CONFIG_DIR}

# -----------------------------------
# EUREKA SERVER [localhost:8071]
# -----------------------------------
  eureka:
    image: imamchishty/eureka-server
    ports:
      - "8071:8071"

# -----------------------------------
# ZUUL SERVER [localhost:8072]
# -----------------------------------
  zuul:
    image: imamchishty/zuul-server
    ports:
      - "8072:8072"
    links:
      - eureka

# -----------------------------------
# TURBINE SERVER [localhost:8073]
# -----------------------------------
  turbine:
    image: imamchishty/turbine-server
    ports:
      - "8073:8073"
    links:
      - eureka

# -----------------------------------
# ZIPKIN SERVER [localhost:9411]
# -----------------------------------
  zipkin:
    image: imamchishty/zipkin-server
    ports:
      - "9411:9411"


